<div>
  <a href="/users">Users</a>
</div>
<div>
  <a href="/users/new">Add user</a>
</div>
<div>
  <hr>
  <form action='<?= $router->urlFor('usersGet') ?>' method='get'>
    <input type='search' required name='term' value=<?= htmlspecialchars($term) ?>>
    <input type='submit' value='Search'>
  </form>
  <?php if (count($flash) > 0): ?>
    <h2 style='color: green'><?= $flash['success'][0] ?></h2>
  <?php endif ?>
  <hr>
</div>
<table>
    <?php foreach($users as $key => $user): ?>
        <?php if (str_contains($user['nickname'], $term)): ?>
            <tr>
                <td>
                    <?= $key ?>
                </td>
                <td>
                    <a href="/users/<?= $key ?>"><?= $user['nickname'] ?></a>
                </td>
                <td>
                    <?= $user['email'] ?>
                </td>
            </tr>
        <?php endif; ?>
    <?php endforeach; ?>
</table>